ENHANCER_FLAGS=-g
ENHANCER_SRC=main.cpp file.cpp image.cpp enhancer.cpp
ENHANCER_HEADERS=file.h image.h enhancer.h
ENHANCER_LIBS=-llept

all: ${ENHANDER_SRC} ${ENHANCER_HEADERS}
	g++ -o scan_enhancer ${ENHANCER_FLAGS} ${ENHANCER_SRC} ${ENHANCER_LIBS}
